### ISSUE TITLE
Add it officially to Home Assistant

### ISSUE THREAD

**Issue by Misiu** [jardiamj/homeassistant#1] opened 2019-04-12 17:21 UTC
I was looking for MCP23017 support for Home Assistant and I found Your repo. Maybe You could add this to official HA repo? I don't know the process but having this officially build in would be awesome!

**Comment by jardiamj** [comment] 2019-04-13 20:06
I looked into that process no long ago and it's in my plans to try to make a Pull Request against the Home Assistant core components. I just don't have enough time at this moment and will probably try in a couple of weeks.
I'm also looking into either deobfuscating the adafruit-mcp23017 library or write one myself and upload it to PyPI.
Another one of my goals is to rewrite the binary_sensor component to use the hardware interrupt pins instead of constantly polling the I/O pins.
Thanks for your interest!

**Comment by Misiu** [comment] 2019-04-14 19:54
@jardiamj thanks for the update.
Isn't `CircuitPython` allowed by Home Assistant? Adafruit has it's library on GitHub - istn't [this one](https://github.com/adafruit/Adafruit_CircuitPython_MCP230xx/blob/master/adafruit_mcp230xx.py) responsible for MCP23017?
[There was a PR](https://github.com/home-assistant/home-assistant/pull/18070) that would add MCP230177 and PCF8574 support, but it got closed.
Maybe code found there can be reused?
Sadly I'm not Python expert, but if You have something ready for MCP23017 and PCF8574 I can try them out - I'm setting up new development Home Assistant instance right now.

**Comment by jardiamj** [comment] 2019-04-14 22:16
Doing a PR for my mcp23017 component should be easy enough since the adrafruit libraries it depends on are already on PyPI.
The reason I am looking into probably writing a new library for it is so I can make use of the hardware interrupt pins.
Give it a try, I'll set up a development HA instance myself to try out what the process for a PR looks like. The component I wrote is simple enough that it might not take me that long, I am just not familiar with the process.

**Comment by Misiu** [comment] 2019-04-15 19:52
I found [this PR ](https://github.com/home-assistant/home-assistant/pull/18070#issuecomment-483146708)in HA repo, it adds MCP23017 and PCF8574 support.
I'm not Python guru (I've started my first course two days ago) but maybe Your code and code by @matkor can be combined? This way support for both extenders could be finally officially added :)

**Comment by jardiamj** [comment] 2019-04-15 21:15
Hi @Misiu,
I took some time to go through the process for a PR on home-assistant core components, here is the link: https://github.com/home-assistant/home-assistant/pull/23127

**Comment by Misiu** [comment] 2019-04-16 06:59
@jardiamj I've noticed that[ this method ](https://github.com/jardiamj/homeassistant/blob/master/custom_components/mcp23017/binary_sensor.py#L73)return True, does that mean that You are not using hardware interrupts?

**Comment by jardiamj** [comment] 2019-04-16 14:46
The Adafruit MCP230xx library doesn't support hardware interrupt, so for the moment this component is polling the pins. You pass scan_interval through the configuration.yaml file.
I am writing a python library that I'll upload to PyPI and will support hardware interrupt, so I can move to use the hardware interrupts.
I tried deobfuscating the Adafruit's library but then came to the conclusion that it was better to write one from zero.
The limiting factor is always finding the time to work on it.

**Comment by jardiamj** [comment] 2019-04-30 18:38
@Misiu, I have implemented the hardware interrupt pins into this component in my local instance of Home Assistance. Unfortunately my laptop stopped booting about a week ago and it seems like the mother board is burnt so I don't currently have a laptop to work on. I ordered a new one but it'll take a week or more to get here and for the time being I am a bit limited in what I can do.
I also saw you comment about improving the documentation with a description on how to connect the MCP23017 to the Raspberry Pi. I think you could help with that if you have the time for it, I'll get back to working on it whenever I get a laptop.

**Comment by Misiu** [comment] 2019-05-06 07:51
@jardiamj sorry to hear that :/ I hope the laptop isn't destroyed because of MCP23017 development.
My current setup requires only 8 relays, so I have them connected directly to Raspberry Pi, but I want to have a minimum 20 before Christmas, so I want to use MCP23017 or similar expander.
I've seen comment by @matkor - https://github.com/home-assistant/home-assistant/pull/23127#issuecomment-485818045 about 3.3V and 5V, so I'm bit scared connecting everything together (I don't want to burn my Raspberry).
I have such modules - https://www.aliexpress.com/item/MCP23017-Serial-Interface-Module-IIC-I2C-SPI-MCP23S17-Bidirectional-16-Bit-I-O-Expander-Pins-10Mhz/32870350461.html in the description there is info that they work up to 5.5Vm but I'm not sure how to connect this module and two 8relay modules together with external power.
I must wait for the second Raspberry Pi and test everything there. If everything works fine I'm more than happy to draw schematics (using Fritzing) showing the correct connection.

P.S. did You use PCF8574 with Home Assistant? It's even more popular than MCP23017.
When Your PR will be merged I can try to create a similar platform for PCF8574. WIll You be able to review it ? I always wanted to try Python, this might be a good opportunity 😊

**Comment by jardiamj** [comment] 2019-05-06 15:56
I believe that my laptop died because I fell down the stairs while carrying it in my hands, I let go of the laptop and it landed a few feet in front of me, the battery and cdrom caddy came off. I thought it was done right there but it still worked for a month or so after that until it died just recently.
The laptop that I have been using for testing the MCP23017 is an old Acer Aspire One that I use for experimenting and it is still working. 
These are the schematics for the IOPI plus developed by Abelectronics.co.uk: https://www.abelectronics.co.uk/docs/pdf/schematic-iopiplus-2-1.pdf
Maybe this will give you an example on how they are connecting the chip and allowing for an external 5v power. They use an Dual N-channel Fet as i2c level converter (FDC6301N) and leave a jumper to the pi's 5v pin, you have to remove this jumper if you want to connect and external 5v to the MCP23017.

BTW, my new laptop is supposed to arrive today.

**Comment by StephenBeirlaen** [comment] 2019-05-08 18:49
I have tested out your latest code with the interrupt trigger on the falling edge, it is working pretty reliably for me!
Maybe it's an idea to submit the interrupt version as well to home assistant :)

But then I would make the 10ms bouncetime an optional variable. It works fine for me, but maybe not for other use cases.

Thank you for these components!

**Comment by jardiamj** [comment] 2019-05-08 21:02
I submitted the PR for the simpler polling version thinking that, it would have a better chance to be accepted. The idea is that once merged, I will implement the hardware interrupt there and... Yes! I'll leave a variable to configure the bouncetime through the configuration.yaml file.

There are two issues I need to solve before the interrupt function would be ready for a Home Assistant PR. The first one is that the current Adafruit's doesn't have a method for reading INCAPA, INCAPB, INTFA or INTFB addresses. As you have seen in my code, I am using an internal function of the library to do that which is a bit hackish.

I will implement those functions in the Adafruit's library and submit a PR against it, maybe this weekend if I can free up some time for it.

The other issue is the one with pins configured as outputs causing some noise on the interrupts when a button is depressed.

Since I can't figure out why that is happening, one of my thoughts is to configure the interrupts as not mirrored and open drain, that way you can link chain them into one pin of the Pi or leave one port for outputs and the other for inputs and connect that one interrupt pin only.

**Comment by jardiamj** [comment] 2019-05-28 20:33
@StephenBeirlaen and @misiu I just wanted to let you guys know that I made a PR on Adafruit's library yesterday, implementing some missing interrupt functionality that would allow me to clean up the code here and get it ready for adding the hardware interrupt logic into the mcp23017 HA component that was recently merged.

Edit: Link to PR: https://github.com/adafruit/Adafruit_CircuitPython_MCP230xx/pull/14

**Comment by StephenBeirlaen** [comment] 2019-05-28 21:35
Great! Looking forward.

**Comment by Misiu** [comment] 2019-05-29 08:34
@jardiamj that's awesome :)
please consider adding an option for the user to be able to pick which option he wants: interrupts or pooling. If I understand correctly interrupts option requires using one additional pin on raspberry

**Comment by jardiamj** [comment] 2019-05-29 15:22
@misiu, I am planning on doing that. You are right the interrupts require you to connect the interrupt pins to a pin in the raspberry pi.
There are 2 interrupt pins, one per port, that can be configured as mirrored. That is, both will get triggered if an interrupt occurs on any pin, on either port.
My plan is to hard code the interrupt pins as open drain. Then, if ```interrupt_port``` is defined in the configuration.yaml it will use interrupts else it will use polling. I also plan on leaving an option for ```mirrored_interrupts``` so if that is set to ```false``` only the interrupt associated with the port where the interrupt occured will be triggered. This way you could still use interrupts and configured inputs and outputs within the same MCP23017, you just need to use one port for inputs and the other for outputs so they don't create the noise that I have experienced in the interrupt pins.
Configuring the pins as open drain would allow you to cascade connect more than one interrupt to the same pin in the Pi, with its pull up resistor enabled of course.

**Comment by StephenBeirlaen** [comment] 2019-07-26 14:45
Just wanted to let you know, your newest interrupt-enabled version of the component is working great here!

**Comment by jardiamj** [comment] 2019-07-26 16:17
Thank you! I need to get the time to integrate the interrupt logic into the HA component that was merged.
Are you using the component for binary sensors only?

**Comment by StephenBeirlaen** [comment] 2019-07-26 16:45
No, I am using switches as well.

**Comment by jardiamj** [comment] 2019-07-26 21:06
Awesome! I have had issues with pins configured as switches creating noise in the interrupt pins. 
I have resorted to having the switches in a separate MCP23017. So, I would like to know if you have experienced the same behavior.

**Comment by StephenBeirlaen** [comment] 2019-08-01 22:56
Strange, I do not notice any problems. Maybe I can see something with my oscilloscope. Can you describe what kind of noise you experience, if it is temporary or the state remains incorrect? I debounce the input with a 47µF capacitor, so maybe the problem lies there instead. I do not like to rely purely on software to debounce my inputs.

A relevant issue with the interrupts I have right now is that I can't reliably use it when I connect the INTA pins of two MCP23017's pins to the same pin on the pi. Probably I need to configure them as  "not mirrored and open drain" as you described earlier, to do this?

**Comment by jardiamj** [comment] 2019-08-06 15:35
When the state is off (window closed), it shows correctly but when the state changes to on (open) it oscillates between on and off. It only happens when there is an output (switch) in the same port.

You should be able to chain link various interrupts to the same pin in the Pi, if they are configured as open drain. The problem is that this component I wrote doesn't have code for identifying and polling the MCP that caused the interrupt.

Any suggestions on the use of the interrupt pins is welcome. I haven't had much time to tinker with it lately.

**Comment by StephenBeirlaen** [comment] 2019-09-09 20:47
Just an update, I had trouble when I connected multiple MCP's to the RPI (with shared INTA pin).
When I connected the same source to a binary_sensor on every MCP (to make both MCP's trigger an interupt simultaneously) I noticed unreliable behaviour. Sometimes, both sensors updated correctly, but usually none, or only one of the two sensors updated in home assistant.

I figured out that this is because if I have multiple MCP23017's defined in my home assistant configuration, the script gets loaded multiple times as well, resulting in multiple GPIO.add_event_detect() calls. This does not seem to work well, triggering this a second time seems to cancel the event in the other script. So only one event listener is actually working. In the event handler, one event can only look for changed pins on the respective MCP the script is running for, not the other MCP('s).

To fix this I rewrote the component to support multiple MCP's in one, with only one global event listener for multiple MCP's.

So this:

```
binary_sensor:
  - platform: mcp23017
    i2c_address: 0x20
    pull_mode: UP
    invert_logic: true
    interrupt_port: 12
    pins:
      8: pin8
      9: pin9
      10: pin10
      11: pin11
      12: pin12
      13: pin13
      14: pin14
      15: pin15
  - platform: mcp23017
    i2c_address: 0x24
    pull_mode: UP
    invert_logic: true
    interrupt_port: 12
    pins:
      8: prototypepcbpin8
```

Becomes this:

```
binary_sensor:
  - platform: mcp23017
    pull_mode: UP
    invert_logic: true
    interrupt_port: 12
    chips:
      - i2c_address: 0x20
        pins:
          8: pin8
          9: pin9
          10: pin10
          11: pin11
          12: pin12
          13: pin13
          14: pin14
          15: pin15
      - i2c_address: 0x24
        pins:
          8: prototypepcbpin8
```

This worked a lot better, but it was still not perfect. Every now and then, a change could not be detected via the intflag registers. Instead, I dispatch an update for every pin... It's a quick fix that I want to avoid, but for now it's the only solutions I've found to work 100% of the time.
If I clean up the code, I'll probably share it here once I find the time.

**Comment by jardiamj** [comment] 2019-09-15 04:21
@StephenBeirlaen. You are right, with my current code every time you define a set of binary mcp23017 sensors in the configuration.yaml a ```GPIO.add_event_detect()``` would be added, and that could cause issues if it gets added multiple time to the same gpio port on the Pi.

I like your approach, please share your code whenever you get the time. Let's get this interrupt logic figured out and then add it to the HA component.
I have had a busy summer but as the rain comes to Seattle I will have more rainy days to do some tinkering with HA.

**Comment by StephenBeirlaen** [comment] 2019-09-15 21:09
Alright, I have opened #5  :)

**Comment by StephenBeirlaen** [comment] 2019-09-17 22:51
Progress...

I have used a cheap logic analyser from Sparkfun (TOL-15033) to measure SCL, SDA and the I2C pin. I have also added 4.7kOhm resistors from SCL and SDA to Vcc, as advised here http://www.circuitbasics.com/basics-of-the-i2c-communication-protocol/ (SINGLE MASTER WITH MULTIPLE SLAVES), just to make sure this is not the issue.
Attached with this post I have a file of a measurement that you can open with PulseView (free).
[Multiple MCP23017 measurement.zip](https://github.com/jardiamj/homeassistant/files/3623707/Multiple.MCP23017.measurement.zip)
After opening the file, you can then add an I2C protocol decoder in the toolbar above to let the software decode the signals for you.

My setup is as follows. I have two boards with each containing an MCP23017.
- breadboard = 0x20, off state of input port B = 0x40 (only pin 14 has something connected, the others are floating)
- pcb = 0x24, off state of input port B = 0xFF (all input pins have something connected)

Pin 8 of 0x24 and pin 14 of 0x20 are both connected to the same input (should be triggering state changes almost simultaneously)

Below I have tried to annotate the measurement in the PulseView file:

When state changes occur, this causes an interrupt, which is detected in our script, then the following happens to detect the states:

```
W	20	0E		INTFA
R	20	00	00	Read INTFA and INTFB
W	20	10		INTCAPA
R	20	00	40	Read INTCAPA and INTCAPB

W	24	0E		INTFA
R	24	00	00	Read INTFA and INTFB
W	24	10		INTCAPA
R	24	00	FF	Read INTCAPA and INTCAPB
```

Nothing was read? Some noise can be seen in the INT pin at 813500µs? Continuing our search...
A little bit later, a second block of data appears at 882 ms:

```
W	20	0E		INTFA
R	20	00	00	Read INTFA and INTFB
W	20	10		INTCAPA
R	20	00	40	Read INTCAPA and INTCAPB

W	24	0E		INTFA
R	24	00	01 !	Read INTFA and INTFB
W	24	10		INTCAPA
R	24	00	FE !	Read INTCAPA and INTCAPB
```

something was read on the 0x24 chip?
shortly afterwards, the following happens:

```
W	24	12		GPIOA
R	24	00	FE	Read GPIOA and GPIOB
```

This is most likely dispatcher_send getting the current status
A few 100ms later at 939ms... Most likely the 0x20 chip also triggers an interrupt. The same block of messages (for the most part) appear:

```
W	20	0E		INTFA
R	20	00	40 !	Read INTFA and INTFB
W	20	10		INTCAPA
R	20	00	00 !	Read INTCAPA and INTCAPB

W	24	0E		INTFA
!W	20	12		GPIOA   dispatcher_send getting the status in between?
R	24	00	00	Read INTFA and INTFB (probably messed up because of the previous write)
!R	20	00	00	Read GPIOA and GPIOB   dispatcher_send getting the status in between? (probably results from wrong register)
W	24	10		INTCAPA
R	24	00	FE !	Read INTCAPA and INTCAPB
```

The order is messed up in the last (third) block! This probably messes up the reads of INTF and INTCAP. I think this might be the problem... Now I'm clueless as to how to prevent the dispatcher_send from sending stuff in between the other communications. Adding delays to dispatcher_send might help, but it's not a 100% guarantee...

Maybe we can prevent the GPIOA reads altogether during the interrupt handlers?

**Comment by StephenBeirlaen** [comment] 2019-09-17 23:01
Or we can add a locking/unlocking mechanism so that I2C communication with the chips is only possible after a "batch" of messages has been sent.

**Comment by Misiu** [comment] 2019-09-18 06:54
@StephenBeirlaen there is a similar platform that was proposed in [this PR](https://github.com/home-assistant/home-assistant/pull/18070), but it didn't get approved.
Sadly I'm no Python expert so it's hard for me to compare both solutions.
@matkor (author of referred PR) is using his code for months now, so maybe he will be able to help/suggest how to fix this issue.
He added batch I²C pin reads and reprogramming to his version, he is also using interrupts so maybe pieces of his code can be reused here.

**Comment by StephenBeirlaen** [comment] 2019-09-18 21:01
I've taken a look at it, but I'm kind of confused, it seems less readable. I can't seem to find the interrupt code :thinking:

**Comment by jardiamj** [comment] 2019-09-19 06:32
Thanks for troubleshooting this issue. If I well understand, the problem is that both chips cause an interrupt almost simultaneously. The first interrupt causes a read from ```INTFA/B``` but only chip ```0x24``` has a flag so a ```dispatcher_send()``` is dispatched to read from it's ```GPIO``` (This read should have cleared the ```INTCAP```).

The problem occurs when chip ```0x20``` causes an interrupt right after and since it's the first chip for which ```INTFA/B``` is read and there is a flag on a pin ```dispatcher_send()``` is dispatched, meanwhile the loop goes into reading the ```INFTA/B``` of chip ```0x24``` while ```dispatcher_send()``` is reading the ```GPIO``` of chip ```0x20``` in between, messing up the whole communication.
I thought that this should not be possible since, according to the documentation for ```adafruit_bus_device.i2c_device``` (mcp23017 depends on it), this reads should lock the i2c bus and the device address: https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/blob/master/adafruit_bus_device/i2c_device.py

I think the read is only locking the device address but not the bus. For testing, we could try inserting a small ```time.sleep()``` at the end of the ```for mcpDict in mcpDicts:``` loop and see if that makes a difference. Like:

```
        for mcpDict in mcpDicts:
            ...
            mcp.clear_ints()
            time.sleep(miliseconds)
```

I also took a look at that PR's code and had a hard time following it but I am not a Python expert either.

I'll merge your changes and tinker a little more with it this weekend. My work schedule is a bit tight these days.

**Comment by matkor** [comment] 2019-09-19 06:58
> I can't seem to find the interrupt code 

There is no interrupt handling in my PR https://github.com/home-assistant/home-assistant/pull/18070

**Comment by jardiamj** [comment] 2019-09-20 00:49
@StephenBeirlaen, in order to lock the i2c bus for each communication batch (loop pass) it seems like we need to initiate the communications in a ```with``` block this way:

```
def update_sensors(port):
    _LOGGER.debug("MCP23017 interrupt detected.")
    for mcpDict in mcpDicts:
        i2c_address = mcpDict.get("i2c_address")
        with busio.I2C(board.SCL, board.SDA) as i2c:
            mcp = MCP23017(i2c, address=i2c_address)
            intflag = mcp.int_flag
            for pin_num in intflag:
                ...
```

And, of course we will need to import ```busio``` and ```board``` in this function.

Can you give this a try and let me know? I won't be able to try it out until Saturday or Sunday.

**Comment by StephenBeirlaen** [comment] 2019-09-20 22:14
Thanks for your ideas.
I tried it out and also had to:
`from adafruit_mcp230xx.mcp23017 import MCP23017`

It did not result in a more reliable inputs, but I have to test and analyse more.
As a side result I could not get switching outputs to work anymore.

I am not sure that piece of code is enough to lock the bus. Don't we need try_lock and unlock for that? https://learn.adafruit.com/circuitpython-basics-i2c-and-spi/i2c-devices

If so, am I correct in thinking that we should stop using CircuitPython's MCP23017 since it does not have locking, and use busio.I2C directly? Or make an alternate version for testing purposes that includes locking.

**Comment by StephenBeirlaen** [comment] 2019-09-20 22:15
> > I can't seem to find the interrupt code
> 
> There is no interrupt handling in my PR [home-assistant/home-assistant#18070](https://github.com/home-assistant/home-assistant/pull/18070)

Ah, that would explain my confusion :laughing:

**Closed as completed** 2019-10-24 05:20 UTC
